apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-08e542b6635d4c91e,subnet-07cf2831592ebe388,subnet-0883f8c6bc0a70876
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
